name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u vanillin --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/vanillin/web-catalog-lepnina-front:latest .

      - name: Push Docker image
        run: docker push ghcr.io/vanillin/web-catalog-lepnina-front:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker if not present
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing..."

            sudo apt-get update
            sudo apt-get install -y \
              ca-certificates \
              curl \
              gnupg \
              lsb-release

            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg

            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
              bookworm stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

            sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

      - name: Log in to GHCR (with sudo)
        run: echo "${{ secrets.GHCR_PAT }}" | sudo docker login ghcr.io -u vanillin --password-stdin

      - name: Pull and deploy frontend (with sudo)
        run: |
          set -e
          cd /home/user/app
          export COMPOSE_INTERACTIVE_NO_CLI=1
          sudo docker-compose pull web-catalog-lepnina-front
          sudo docker-compose up -d web-catalog-lepnina-front
